name:                HLasm
version:             0.1.0.0
github:              "vorotynsky/HLasm"
license:             GPL-3
author:              "Vorotynsky Maxim"
maintainer:          "vorotynsky.maxim@gmail.com"
copyright:           "2020 Vorotynsky Maxim"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/vorotynsky/HLasm#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6 && < 0.7
- extra >= 1.0 && < 1.8
- parsec >= 3.1.0 && <= 3.1.14.0

library:
  source-dirs: src

executables:
  HLasm-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HLasm
